### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by SilvaQ** [gheyret/UyghurSpell#2]
gheyret 长辈好，
我在 u-open-imla 项目中给自己建立了一份项目禁用词列表 [禁用词列表](https://github.com/ishirkhan/u-open-imla/tree/main/banned_words) 。如果长辈觉得这个禁用词也可以用于本项目的话，望在本项目的imla.txt中也清除这些禁用词，尽可能一起扩展并维护一个统一的项目禁用词表。

**Comment by gheyret** [comment]
Kechurung, ishlitidighanlar ozliri chiqiriwetip ishletsun.

**Comment by SilvaQ** [comment]
可以考虑转码保存，并明文给出还原原始数据的方法或工具。
我们使用者大部分不动程序。他们直接下载或者从其他渠道达到软件并使用。甚至为了收藏将保存一些网络网盘上。这种情况下文本内容容易被扫描。所以我们如果可以的话更多的为哪些使用软件但是不知道程序，或者没有能力做一些安全处理的人考虑的话我想是更好的一件事儿。当然我了解长辈的初衷。只是如果能避免好事儿变成坏事儿就好了。

还有希望长辈看完issue 后麻烦删除一下本issue
